export const emojiMovieMappings = [
    { movie: 'Star Wars', emojis: '⚔️🚀✨' },
    { movie: 'The Lion King', emojis: '🦁👑🌅' },
    { movie: 'Titanic', emojis: '🚢❤️💔' },
    { movie: 'The Matrix', emojis: '💊🕶️💻' },
    { movie: 'Jurassic Park', emojis: '🦖🏝️😱' },
    { movie: 'Avatar', emojis: '🌌👽🦾🌿' },
    { movie: 'Finding Nemo', emojis: '🐟🌊🔍' },
    { movie: 'Inception', emojis: '🌀💤🏙️' },
    { movie: 'The Godfather', emojis: '🧔🔫💼' },
    { movie: 'Harry Potter', emojis: '⚡🧙‍♂️🏰' },
    { movie: 'The Avengers', emojis: '🦸‍♂️🦸‍♀️🌍' },
    { movie: 'Back to the Future', emojis: '⏰🚗👨‍🔬' },
    { movie: 'The Dark Knight', emojis: '🦇🎭🏙️' },
    { movie: 'Forrest Gump', emojis: '🏃‍♂️🍫🪑' },
    { movie: 'Frozen', emojis: '❄️👸⛄' },
    { movie: 'Moana', emojis: '🌊🚣‍♀️🌺' },
    { movie: 'Aladdin', emojis: '🧞‍♂️🕌💫' },
    { movie: 'Pirates of the Caribbean', emojis: '🏴‍☠️⚔️🚢' },
    { movie: 'Coco', emojis: '🎸💀🌺' },
    { movie: 'WALL-E', emojis: '🤖🌍🚀' },
    { movie: 'Toy Story', emojis: '🤠🧸👽' },
    { movie: 'The Hunger Games', emojis: '🏹🔥🏛️' },
    { movie: 'The Incredibles', emojis: '🦸‍♂️🦸‍♀️💥' },
    { movie: 'The Terminator', emojis: '🤖🔫🔥' },
    { movie: 'Rocky', emojis: '🥊🏆🇺🇸' },
    { movie: 'Mulan', emojis: '👸⚔️🐉' },
    { movie: 'E.T. the Extra-Terrestrial', emojis: '👽👦🚲🌕' },
    { movie: 'Shrek', emojis: '👹👸🐉' },
    { movie: 'The Wizard of Oz', emojis: '🌪️🧙‍♂️🦁' },
    { movie: 'The Lion King', emojis: '🦁👑🌅' },
    { movie: 'Jaws', emojis: '🦈🚤🏖️' },
    { movie: 'Good Will Hunting', emojis: '📚🧠💔' },
    { movie: 'Gladiator', emojis: '⚔️🛡️🏛️' },
    { movie: 'The Sound of Music', emojis: '🎶⛰️🇦🇹' },
    { movie: 'Indiana Jones', emojis: '🏺🧭🐍' },
    { movie: 'The Shawshank Redemption', emojis: '⛓️🏢🌧️' }
];